spring:
  config:
    activate:
      on-profile: dev

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:8000"
              - "http://localhost"

      routes:
        - id: minerreport-backend-datamart-producer-docs
          uri: http://localhost:8003
          predicates:
            - Path=/producer/index.html

        - id: minerreport-backend-datamart-producer-docs
          uri: http://localhost:8003
          predicates:
            - Path=/producer/swagger-ui/**

        - id: minerreport-backend-datamart-producer-docs
          uri: http://localhost:8003
          predicates:
            - Path=/producer/v3/api-docs/**

        - id: minerreport-backend-datamart-batch
          uri: http://localhost:8005
          predicates:
            - Path=/v1/api/batch/**

        - id: minerreport-backend-datamart-batch-docs
          uri: http://localhost:8005
          predicates:
            - Path=/batch/index.html

        - id: minerreport-backend-datamart-batch-docs
          uri: http://localhost:8005
          predicates:
            - Path=/batch/swagger-ui/**

        - id: minerreport-backend-datamart-batch-docs
          uri: http://localhost:8005
          predicates:
            - Path=/batch/v3/api-docs/**

        - id: minerreport-backend-workflow
          uri: http://localhost:8006
          predicates:
            - Path=/v1/api/wf/**